---

### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "ndom91"
keywords:    "Singlepaged, jekyll, github, blog, resume, nico domino"
description: "ndom91 resume"
source_link: "https://github.com/t413/SinglePaged"
favicon:     "img/ndo_logo64.png"
touch_icon:  "img/ndo_logo64.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#264653'
  green:     '#9bcf2f'
  purple:    '#e9c46a'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false

# sudo jekyll build --verbose --destination /var/www/html/resume
